apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: docker.io/neptuneg/user-service:latest
        env:
          - name: DB_HOST
            value: db.db.svc.cluster.local
          - name: DB_NAME
            value: user_development
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: psql
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql
                key: password
        ports:
        - containerPort: 3377
        resources:
          limits:
            memory: 128Mi
            cpu: "0.3"
          requests:
            memory: 64Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3377
      targetPort: 3377
