apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: docker.io/neptuneg/auth-service:latest
        env:
          - name: DB_HOST
            value: db.db.svc.cluster.local
          - name: DB_NAME
            value: auth_development
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: psql
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql
                key: password
        ports:
        - containerPort: 3377
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3377
      targetPort: 3377
