apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    version: v1
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      containers:
      - name: payment
        image: quay.io/goss_beta/payment-service:latest
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DB_NAME
            value: payment_development
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: psql
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql
                key: password
          - name: GRPC_GO_RETRY
            value: 'on'
        ports:
        - containerPort: 3377
          protocol: TCP
          name: grpc
        readinessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        livenessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - protocol: TCP
      appProtocol: grpc
      name: grpc
      port: 3377
      targetPort: 3377
