apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: app-config
data:
  TZ: "Asia/Tokyo"
  REDIS_CACHE_SERVICE_HOST: redis-cache.{{ .Release.Namespace }}.svc.cluster.local
  REDIS_CACHE_SERVICE_PORT: "6379"
  REDIS_MQ_SERVICE_HOST: redis-mq.{{ .Release.Namespace }}.svc.cluster.local
  REDIS_MQ_SERVICE_PORT: "6379"
  DB_HOST: db.{{ .Release.Namespace }}.svc.cluster.local
  FAKTORY_PROVIDER: "FAKTORY_URL"
  FAKTORY_URL: "tcp://faktory.{{ .Release.Namespace }}.svc.cluster.local:7419"
  DTM_HOST: dtm.{{ .Release.Namespace }}.svc.cluster.local
  DTM_GRPC_PORT: "36790"
