apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  TZ: "Asia/Tokyo"
  REDIS_CACHE_SERVICE_HOST: redis-cache.default.svc.cluster.local
  REDIS_CACHE_SERVICE_PORT: "6379"
  REDIS_MQ_SERVICE_HOST: redis-mq.default.svc.cluster.local
  REDIS_MQ_SERVICE_PORT: "6379"
  DB_HOST: db.default.svc.cluster.local
  FAKTORY_PROVIDER: "FAKTORY_URL"
  FAKTORY_URL: "tcp://faktory.default.svc.cluster.local:7419"
  DTM_HOST: dtm.default.svc.cluster.local
  DTM_GRPC_PORT: "36790"
