apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm
  labels:
    app: dtm
    version: v1
    {{- include "go-back.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtm
      version: v1
  template:
    metadata:
      labels:
        app: dtm
        version: v1
    spec:
      containers:
      - name: dtm
        image: "{{ .Values.dtm.image.repository }}:{{ .Values.dtm.image.tag }}"
        imagePullPolicy: {{ .Values.dtm.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 36790
          protocol: TCP
          name: grpc
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: dtm
  labels:
    {{- include "go-back.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: dtm
  ports:
    - protocol: TCP
      appProtocol: grpc
      name: grpc
      port: 36790
      targetPort: 36790
