apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: faktory-workers
  labels:
    app: faktory-workers
    version: v1
    {{- include "go-back.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faktory-workers
      version: v1
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: faktory-workers
        version: v1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: faktory-workers
        image: "{{ .Values.faktory_workers.image.repository }}:{{ .Values.faktory_workers.image.tag }}"
        imagePullPolicy: {{ .Values.faktory_workers.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          limits:
            memory: 128Mi
            cpu: "0.3"
          requests:
            memory: 64Mi
            cpu: "0.1"
