apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: gateway
  labels:
    app: gateway
    version: v1
    {{- include "go-back.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        ports:
        - containerPort: 4000
          protocol: TCP
          name: http
        - containerPort: 3377
          protocol: TCP
          name: grpc
        readinessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        livenessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: gateway
  labels:
    {{- include "go-back.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      appProtocol: http
      name: http
      port: 4000
      targetPort: 4000
    - protocol: TCP
      appProtocol: grpc
      name: grpc
      port: 3377
      targetPort: 3377
