apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
  labels:
    app: live
    version: v1
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live
      version: v1
  template:
    metadata:
      labels:
        app: live
        version: v1
    spec:
      containers:
      - name: live
        image: "{{ .Values.live.image.repository }}:{{ .Values.live.image.tag }}"
        imagePullPolicy: {{ .Values.live.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DB_NAME
            value: live_development
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: psql
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql
                key: password
        ports:
        - containerPort: 3377
          protocol: TCP
          name: grpc
        readinessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        livenessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: live
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: live
  ports:
    - protocol: TCP
      appProtocol: grpc
      name: grpc
      port: 3377
      targetPort: 3377
