apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    istio-injection: enabled
