apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: scraper
    version: v1
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
      version: v1
  template:
    metadata:
      labels:
        app: scraper
        version: v1
    spec:
      containers:
      - name: scraper
        image: "{{ .Values.scraper.image.repository }}:{{ .Values.scraper.image.tag }}"
        imagePullPolicy: {{ .Values.scraper.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 3377
          protocol: TCP
          name: grpc
        readinessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        livenessProbe:
          exec:
            command: [ "/app/grpc-health-probe", "-addr=:3377" ]
        resources:
          limits:
            memory: 32Mi
            cpu: "0.3"
          requests:
            memory: 16Mi
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: scraper
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: scraper
  ports:
    - protocol: TCP
      appProtocol: grpc
      name: grpc
      port: 3377
      targetPort: 3377
